### ISSUE TITLE
unexpected keyword argument projection

### ISSUE THREAD

**Issue by spyder98web** [AppScale/appscale#1679]
helloworld.py:
```python
class Address(ndb.Model):
    type = ndb.StringProperty() # E.g., 'home', 'work'
    street = ndb.StringProperty()
    city = ndb.StringProperty()

class Contact(ndb.Model):
    name = ndb.StringProperty()
    address = ndb.StructuredProperty(Address)

class MainPage(webapp.RequestHandler):
    def get(self):
        Contact.query(projection=["address.city"], distinct=True)
```

error:
```python
__init__() got an unexpected keyword argument 'projection'
Traceback (most recent call last):
File "/root/appscale/AppServer/lib/webapp2-2.3/webapp2.py", line 1511, in __call__
rv = self.handle_exception(request, response, e)
File "/root/appscale/AppServer/lib/webapp2-2.3/webapp2.py", line 1505, in __call__
rv = self.router.dispatch(request, response)
File "/root/appscale/AppServer/lib/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
return route.handler_adapter(request, response)
File "/root/appscale/AppServer/lib/webapp2-2.3/webapp2.py", line 1077, in __call__
return handler.dispatch()
File "/root/appscale/AppServer/lib/webapp2-2.3/webapp2.py", line 547, in dispatch
return self.handle_exception(e, self.app.debug)
File "/root/appscale/AppServer/lib/webapp2-2.3/webapp2.py", line 545, in dispatch
return method(*args, **kwargs)
File "/var/apps/helloworld/app/helloworld.py", line 18, in get
Contact.query(projection=["address.city"], distinct=True)
File "/root/appscale/AppServer/google/appengine/ext/ndb/model.py", line 3187, in _query
qry = Query(kind=cls._get_kind(), **kwds)
File "/root/appscale/AppServer/google/appengine/ext/ndb/utils.py", line 136, in positional_wrapper
return wrapped(*args, **kwds)
TypeError: __init__() got an unexpected keyword argument 'projection'
```

**Comment by nlake44** [comment]
Do you get the same exception if you do the projection argument in the "fetch" of the query?

**Comment by spyder98web** [comment]
No, but then I get an error about the "distinct" keyword argument. I don't know how to perform fetch with distinct.

**Comment by nlake44** [comment]
Try using the "group_by" argument as explained here:
https://cloud.google.com/appengine/docs/python/ndb/queries

I'm currently working on upgrading ndb to the latest version (so that you're initial issues are fixed). Hopefully we'll get that in for the 2.2. release.

**Comment by nlake44** [comment]
In the meantime, if you would like to get the latest version of NDB you can download the latest GAE SDK and copy over the contents of google/appengine/ext/ndb into appscale/AppServer/google/appengine/ext/ndb. Then just re-upload your app. 

There are a few issues that the new NDB exposed (nothing critical) but we'll have those fixes in master soon.

Thanks!
-Raj

**Comment by nlake44** [comment]
Master now has the latest version of NDB. Closing this issue.

**Comment by spyder98web** [comment]
Tested with the latest version and it worked. Thanks!

**Comment by nlake44** [comment]
Great! Feel free to let us know of any other issues. :smile:
