### ISSUE TITLE
Issues uploading large files to blobstore

### ISSUE THREAD

**Issue by zeroluck** [AppScale/appscale#1902]
I am having issues uploading larger files to my App on AppScale. My app is showing some errors, but I'm not sure if they are directly related or what they mean:

```
POST to uploadpkg not from Blobstore: {'Upgrade-Insecure-Requests': '1', 'Accept-Language': 'en-US,en;q=0.8', 'X-Real-Ip': '192.168.20.31', 'Content_Type': 'multipart/form-data; boundary="===============5196102086632808421=="', 'X-Forwarded-Ssl': 'on', 'X-Forwarded-For': '192.168.20.31', 'Cookie': 'dev_appserver_login=admin%40brewerscience.com%3Aadmin%3Asimian%3A427c8b432b0e2988327d8b7d56fe9201f07365e7', 'Referer': 'https://simian.brewerscience.com/admin/uploadpkg?filename=FileZilla_3.11.0.2_macosx-x86.app.tar.bz2.dmg', 'Origin': 'https://simian.brewerscience.com', 'Cache-Control': 'max-age=0', 'Host': 'simian.brewerscience.com', 'Content-Type': 'multipart/form-data; boundary="===============5196102086632808421=="', 'Content-Length': '582', 'X-Appengine-Country': 'ZZ', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Content_Length': '582', 'X-Forwarded-Proto': 'https', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36'}
```

Another entry shows:

```
Datastore connection error on run_query request.
Traceback (most recent call last):
File "/root/appscale/AppServer/lib/webapp2-2.5.2/webapp2.py", line 1535, in __call__
rv = self.handle_exception(request, response, e)
File "/root/appscale/AppServer/lib/webapp2-2.5.2/webapp2.py", line 1529, in __call__
rv = self.router.dispatch(request, response)
File "/root/appscale/AppServer/lib/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
return route.handler_adapter(request, response)
File "/root/appscale/AppServer/lib/webapp2-2.5.2/webapp2.py", line 1102, in __call__
return handler.dispatch()
File "/root/appscale/AppServer/lib/webapp2-2.5.2/webapp2.py", line 572, in dispatch
return self.handle_exception(e, self.app.debug)
File "/var/apps/simian/app/simian/mac/admin/__init__.py", line 153, in handle_exception
super(AdminHandler, self).handle_exception(exception, debug_mode)
File "/root/appscale/AppServer/lib/webapp2-2.5.2/webapp2.py", line 570, in dispatch
return method(*args, **kwargs)
File "/var/apps/simian/app/simian/mac/admin/packages.py", line 57, in get
self._DisplayPackagesList()
File "/var/apps/simian/app/simian/mac/admin/packages.py", line 74, in _DisplayPackagesList
for p in query:
File "/root/appscale/AppServer/google/appengine/ext/db/__init__.py", line 2326, in next
return self.__model_class.from_entity(self.__iterator.next())
File "/root/appscale/AppServer/google/appengine/api/datastore.py", line 2256, in IterateResults
heap_value = MultiQuery.SortOrderEntity(result, self.__orderings)
File "/root/appscale/AppServer/google/appengine/api/datastore.py", line 2047, in __init__
self.__entity = entity_iterator.next()
File "/root/appscale/AppServer/google/appengine/datastore/datastore_query.py", line 2892, in next
next_batch = self.__batcher.next()
File "/root/appscale/AppServer/google/appengine/datastore/datastore_query.py", line 2754, in next
return self.next_batch(self.AT_LEAST_ONE)
File "/root/appscale/AppServer/google/appengine/datastore/datastore_query.py", line 2791, in next_batch
batch = self.__next_batch.get_result()
File "/root/appscale/AppServer/google/appengine/api/apiproxy_stub_map.py", line 615, in get_result
return self.__get_result_hook(self)
File "/root/appscale/AppServer/google/appengine/datastore/datastore_query.py", line 2528, in __query_result_hook
self._batch_shared.conn.check_rpc_success(rpc)
File "/root/appscale/AppServer/google/appengine/datastore/datastore_rpc.py", line 1224, in check_rpc_success
raise _ToDatastoreError(err)
InternalError: Datastore connection error on run_query request.
```

I can provide complete logs if that would be helpful.

**Comment by menivaitsi** [comment]
Hi there,

What is the size of the file you're trying to upload?

Can you send full logs of the process to meni@appscale.com? You can collect
them by running: *appscale logs /root/upload-logs*.

Thanks
-Meni

--
Meni Vaitsi
Software Engineer
AppScale Systems, Inc.

**Comment by zeroluck** [comment]
I've sent the logs via Google Drive. Please let me know if you need more logs or anything! Thanks!

**Comment by menivaitsi** [comment]
Thank you for sending those over. I'll take a look.

**Comment by menivaitsi** [comment]
So after taking a look at the logs, it seems you're trying to upload very large blobs.

On Google App Engine the limit for blob uploads is 32MB.
On AppScale we have a tested limit of 200MB, even though depending on the system load the actual upper limit can be quite higher than this.

We can come up with a list of places in the code where limits and timeouts are imposed and put it into a wiki page so you can tweak them if you want. However, increasing the timeouts may cause performance degradation in some cases.

Closing this.

**Comment by zeroluck** [comment]
Did you ever get a chance to list the places in the code where limits and timeouts are imposed? I am seeing people reporting being able to upload large files to the blobstore on GAE (7GB) https://goo.gl/8xo7Yi

I think since I am on gigabit LAN with my AppScale instance and it is on fast hardware it should be physically possible to upload larger files to my AppScale instance.
