### ISSUE TITLE
coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by optimizedsms** [AppScale/appscale#1943]
Thoughts on this error?
I am try to deploy to an new installation.
-Mike

A log with more information is available at
/Users/mike/.appscale/log-7833ff27-0e7e-4612-b366-cf66247380e5.
Michaels-Mac-mini:appscale mike$ cat ../.appscale/log-f2dfc425-399a-47a1-875d-744e247f772f 
stacktrace : Traceback (most recent call last):
  File "/usr/local/Cellar/appscale-tools/2.6.0/libexec/bin/appscale", line 92, in <module>
    appscale.deploy(sys.argv[2])
  File "/usr/local/Cellar/appscale-tools/2.6.0/libexec/lib/python2.7/site-packages/appscale/appscale.py", line 496, in deploy
    return AppScaleTools.upload_app(options)
  File "/usr/local/Cellar/appscale-tools/2.6.0/libexec/lib/python2.7/site-packages/appscale/appscale_tools.py", line 570, in upload_app
    app_id = AppEngineHelper.get_app_id_from_app_config(file_location)
  File "/usr/local/Cellar/appscale-tools/2.6.0/libexec/lib/python2.7/site-packages/appscale/appengine_helper.py", line 173, in get_app_id_from_app_config
    app_config_file = cls.get_config_file_from_dir(app_dir)
  File "/usr/local/Cellar/appscale-tools/2.6.0/libexec/lib/python2.7/site-packages/appscale/appengine_helper.py", line 240, in get_config_file_from_dir
    elif os.path.exists(cls.get_appengine_web_xml_location(app_dir)):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

exception : TypeError

locale : en_US

tools_version : 2.6.0

platform : Darwin-15.3.0-x86_64-i386-64bit

message : coercing to Unicode: need string or buffer, NoneType found

runtime : CPython

**Comment by menivaitsi** [comment]
Hi Mike,

Can you post the appscale deploy command you run before getting this error?

**Comment by optimizedsms** [comment]
Yes, thank you.

I  have tried:
appscale deploy ~/HappyClass/happy-class.tar.gz
and:
appscale deploy /Users/mike/HappyClass/happy-class
and:
appscale deploy ~/HappyClass/happy-class/

I am running on a MAC if that makes any difference.

Thank you!

**Comment by menivaitsi** [comment]
The deploy commands look fine.
What's the output of:

   -
*ls ~/HappyClass/happy-class/ *
   - *tar tvzf ~/HappyClass/happy-class.tar.gz*


Thanks!



--
Meni Vaitsi
Software Engineer
AppScale Systems, Inc.
