### ISSUE TITLE
Can't install appscale on fresh ubuntu-xenial

### ISSUE THREAD

**Issue by emli** [AppScale/appscale#2767]
I am running script that provided in official site of appscale
`wget -O bootstrap.sh https://bootstrap.appscale.com && bash ./bootstrap.sh`

```3 gems installed
'/root/appscale/AppDashboard/setup/haproxy.cfg' -> '/etc/haproxy/haproxy.cfg'
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "en_US.UTF-8",
	LC_PAPER = "ky_KG",
	LC_ADDRESS = "ky_KG",
	LC_MONETARY = "ky_KG",
	LC_NUMERIC = "ky_KG",
	LC_TELEPHONE = "ky_KG",
	LC_IDENTIFICATION = "ky_KG",
	LC_MEASUREMENT = "ky_KG",
	LC_TIME = "ky_KG",
	LC_NAME = "ky_KG",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
insserv: warning: current start runlevel(s) (empty) of script `haproxy' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `haproxy' overrides LSB defaults (0 1 6).
removed '/etc/nginx/sites-enabled/default'
Fetching http://s3.amazonaws.com/appscale-build/appengine-java-sdk-1.8.4.zip
Buildfile: /root/appscale/AppServer_Java/build.xml

clean-all:

BUILD SUCCESSFUL
Total time: 0 seconds
Extracting Java SDK
Fetching http://s3.amazonaws.com/appscale-build/repackaged-appengine-eclipse-jdt-ecj.jar
Buildfile: /root/appscale/AppServer_Java/build.xml

repack-sdk:
    [mkdir] Created dir: /root/appscale/AppServer_Java/appengine-java-sdk-repacked
     [copy] Copying 96 files to /root/appscale/AppServer_Java/appengine-java-sdk-repacked
     [copy] Copying 18 files to /root/appscale/AppServer_Java/appengine-java-sdk-repacked/lib/impl
    [chmod] Applied chmod to 4 files and 0 directories.

compile:
    [mkdir] Created dir: /root/appscale/AppServer_Java/build
    [javac] Compiling 48 source files to /root/appscale/AppServer_Java/build
    [javac] /root/appscale/AppServer_Java/src/com/google/appengine/tools/development/agent/runtime/Runtime.java:9: warning: Reflection is internal proprietary API and may be removed in a future release
    [javac] import sun.reflect.Reflection;
    [javac]                   ^
    [javac] /root/appscale/AppServer_Java/src/com/google/appengine/tools/development/agent/runtime/Runtime.java:9: warning: Reflection is internal proprietary API and may be removed in a future release
    [javac] import sun.reflect.Reflection;
    [javac]                   ^
    [javac] /root/appscale/AppServer_Java/src/com/google/appengine/tools/development/agent/runtime/Runtime.java:9: warning: Reflection is internal proprietary API and may be removed in a future release
    [javac] import sun.reflect.Reflection;
    [javac]                   ^
    [javac] /root/appscale/AppServer_Java/src/com/google/appengine/tools/development/agent/runtime/Runtime.java:434: warning: Reflection is internal proprietary API and may be removed in a future release
    [javac]         return Reflection.getCallerClass(depth + 4);
    [javac]                ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 4 warnings
     [copy] Copying 1 file to /root/appscale/AppServer_Java/build/apphosting/tools

update-api-jar-user:
      [jar] Updating jar: /root/appscale/AppServer_Java/appengine-java-sdk-repacked/lib/user/appengine-api-1.0-sdk-1.8.4.jar
    [unzip] Expanding: /root/appscale/AppServer_Java/appengine-java-sdk-repacked/lib/user/appengine-api-1.0-sdk-1.8.4.jar into /root/appscale/AppServer_Java/appengine-java-sdk-repacked/lib/user/tmp
   [delete] Deleting directory /root/appscale/AppServer_Java/appengine-java-sdk-repacked/lib/user/tmp/javax/mail
   [delete] Deleting directory /root/appscale/AppServer_Java/appengine-java-sdk-repacked/lib/user/tmp/javax/activation
      [jar] Building jar: /root/appscale/AppServer_Java/appengine-java-sdk-repacked/lib/user/appengine-api-1.0-sdk-1.8.4.jar
   [delete] Deleting directory /root/appscale/AppServer_Java/appengine-java-sdk-repacked/lib/user/tmp

update-api-jar:
      [jar] Updating jar: /root/appscale/AppServer_Java/appengine-java-sdk-repacked/lib/impl/appengine-api.jar
    [unzip] Expanding: /root/appscale/AppServer_Java/appengine-java-sdk-repacked/lib/impl/appengine-api.jar into /root/appscale/AppServer_Java/appengine-java-sdk-repacked/lib/impl/tmp
   [delete] Deleting directory /root/appscale/AppServer_Java/appengine-java-sdk-repacked/lib/impl/tmp/javax/mail
   [delete] Deleting directory /root/appscale/AppServer_Java/appengine-java-sdk-repacked/lib/impl/tmp/javax/activation
      [jar] Building jar: /root/appscale/AppServer_Java/appengine-java-sdk-repacked/lib/impl/appengine-api.jar
   [delete] Deleting directory /root/appscale/AppServer_Java/appengine-java-sdk-repacked/lib/impl/tmp

update-agent-runtime-jar:
      [jar] Updating jar: /root/appscale/AppServer_Java/appengine-java-sdk-repacked/lib/impl/agent/appengine-agentruntime.jar

update-api-stubs-jar:
    [unjar] Expanding: /root/appscale/AppServer_Java/appengine-java-sdk-repacked/lib/impl/appengine-api-stubs.jar into /root/appscale/AppServer_Java/build
      [jar] Updating jar: /root/appscale/AppServer_Java/appengine-java-sdk-repacked/lib/impl/appengine-api-stubs.jar

update-local-runtime-jar:
      [jar] Updating jar: /root/appscale/AppServer_Java/appengine-java-sdk-repacked/lib/impl/appengine-local-runtime.jar
     [copy] Copying 1 file to /root/appscale/AppServer_Java/appengine-java-sdk-repacked/com/google/appengine/tools

update-tools-api-jar:
      [jar] Updating jar: /root/appscale/AppServer_Java/appengine-java-sdk-repacked/lib/appengine-tools-api.jar

update-remote-jar:
      [jar] Updating jar: /root/appscale/AppServer_Java/appengine-java-sdk-repacked/lib/appengine-remote-api.jar

update-jars:

install:

BUILD SUCCESSFUL
Total time: 1 minute 34 seconds
Buildfile: /root/appscale/AppServer_Java/build.xml

clean-build:
   [delete] Deleting directory /root/appscale/AppServer_Java/build
   [delete] Deleting directory /root/appscale/AppServer_Java/appengine-java-sdk-1.8.4

BUILD SUCCESSFUL
Total time: 0 seconds
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
Failed to install tornado==4.2.0: retrying ...
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
Failed to install tornado==4.2.0: retrying ...
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
Failed to install tornado==4.2.0: retrying ...
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
Failed to install tornado==4.2.0: retrying ...
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
Failed to install tornado==4.2.0: retrying ...
Failed to install tornado==4.2.0: giving up.
failed!
root@Container-1-V3o:~# uname -a
Linux Container-1-V3o 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 x86_64 x86_64 GNU/Linux
root@Container-1-V3o:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
root@Container-1-V3o:~#```

**Comment by cdonati** [comment]
At first glance, it seems to be a locale-related issue. My guess is that it doesn't like that `LANGUAGE` is unset.

I would recommend defining it explicitly. For example, something like
```
export LANGUAGE="en_US.UTF-8"
echo 'LANGUAGE="en_US.UTF-8"' >> /etc/default/locale
```
If the build still fails after that due to a locale-related issue, [this wiki page](https://help.ubuntu.com/community/Locale) may be useful.

**Comment by emli** [comment]
@cdonati 
```
sudo apt-get install apt-transport-https locales sudo wget
sudo locale-gen en_US.UTF-8
sudo echo "LANG=en_US.UTF-8" > /etc/default/locale
```
Solved with this issue.

But get new kind of error
```# Added by AppScale: this is needed to have a working monit command
set httpd port 2812 and
   use address localhost  # only accept connection from localhost
   allow localhost
insserv: warning: current start runlevel(s) (empty) of script `monit' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `monit' overrides LSB defaults (0 1 6).
'/etc/hosts' -> '/etc/hosts.orig'
Generating /etc/hosts
127.0.0.1       localhost localhost.localdomain
127.0.1.1 Container-1-HP2
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
root            hard    nofile           200000
root            soft    nofile           200000
*               hard    nofile           200000
*               soft    nofile           200000
*               -       nproc            32768
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.9.0-6-amd64/modules.dep.bin'
modprobe: FATAL: Module ip_conntrack not found in directory /lib/modules/4.9.0-6-amd64
sysctl: cannot stat /proc/sys/net/netfilter/nf_conntrack_max: No such file or directory
sysctl: cannot stat /proc/sys/net/core/somaxconn: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv4/tcp_tw_reuse: No such file or directory
net.ipv4.tcp_orphan_retries = 1
net.ipv4.tcp_fin_timeout = 25
sysctl: cannot stat /proc/sys/net/ipv4/tcp_max_orphans: No such file or directory
net.ipv4.ip_local_port_range = 32768 61000
failed!
```

**Comment by cdonati** [comment]
From your hostname (Container-1-V3o), I assume you are installing in a container rather than a VM. The section you encountered an error in should not be running under docker.

If you are trying to run AppScale in a non-docker container, you may run into some issues since we haven't tested that setup before. That said, you could try convincing the build script that you are using docker by changing [this line](https://github.com/AppScale/appscale/blob/6d08202f7dfc68692c19a2758e1e3f1a651bb4a9/debian/appscale_build.sh#L55) to `export IN_DOCKER="yes"`. If you later use script/fast-start.sh, you should also change [this line](https://github.com/AppScale/appscale/blob/6d08202f7dfc68692c19a2758e1e3f1a651bb4a9/scripts/fast-start.sh#L22) to `PROVIDER="Docker" && /usr/sbin/sshd && /usr/sbin/cron`.

**Comment by emli** [comment]
@cdonati It isn't docker container. Please provide another solutions /scripts.

**Comment by cdonati** [comment]
I understand that it's not a docker container. My point is that your host name (and the inabilty of sysctl to adjust kernel parameters) indicates that you are using a different kind of container (like LXC for example). If you are running in a container, the build script would be more likely to succeed if it believes it's running in a docker container (since that is the only container type we've tested with).

Of course, I may have made an incorrect assumption about you running in a container. Could you provide some more information about what kind of infrastructure you are trying to install AppScale on? Is it bare metal? a virtual machine? a non-docker container?

**Comment by emli** [comment]
@cdonati I see, thank you nice explanation.

It is LXC container. I can give access to container if you want.
