### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by pcoenen** [AppScale/appscale#2823]
When installing appScale on Ubuntu 16, I always get the following error

```
Installing collected packages: pycapnp
  Running setup.py install for pycapnp ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-LI21Iu/pycapnp/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Vtkv9S-record/install-record.txt --single-version-externally-managed --compile:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-LI21Iu/pycapnp/setup.py", line 92, in <module>
        from Cython.Distutils import build_ext as build_ext_c
    ImportError: No module named Cython.Distutils

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-LI21Iu/pycapnp/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Vtkv9S-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-LI21Iu/pycapnp/
You are using pip version 8.1.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Failed to install pycapnp: retrying ...
```

**Comment by cdonati** [comment]
Hi @pcoenen,

That's the first time I've seen that issue. Would you mind sharing a few details about the environment you are installing AppScale on? Is this a virtual machine, container, or bare metal? What's your CPU architecture (`lscpu`)? Are you installing as the root user?

pycapnp should be installing whatever dependencies it needs before building, but you could try running  `pip install cython` before running the AppScale build.

**Comment by obino** [comment]
Closing for no response in a long time: please re-open if needed.

**Comment by kerbymart** [comment]
@pcoenen @cdonati 

```
pip install Cython==0.29.21
```

Then use an older version of `pycapnp` otherwise it will throw errors: https://github.com/AppScale/gts/issues/3232

```
git clone -b v0.6.4 https://github.com/capnproto/pycapnp.git
```

**Comment by kerbymart** [comment]
Hi @obino, I believe this issue should be reopened since 'bootstrap.sh' no longer builds Appscale.
